CREATE TABLE CUSTOMERS (
CUSTOMER_ID INT PRIMARY KEY,
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
AGE INT,
COUNTRY VARCHAR(50)
);

CREATE TABLE ORDERS (
ORDER_ID INT PRIMARY KEY,
ITEM VARCHAR(50),
AMOUNT INT,
CUSTOMER_ID INT REFERENCES CUSTOMERS(CUSTOMER_ID)
);

CREATE TABLE SHIPPINGS (
SHIPPING_ID INT PRIMARY KEY,
STATUS VARCHAR(20),
CUSTOMER INT REFERENCES CUSTOMERS(CUSTOMER_ID)
);


INSERT INTO CUSTOMERS (CUSTOMER_ID,FIRST_NAME,LAST_NAME,AGE,COUNTRY) VALUES 
(1, 'JOHN', 'DOE', 31, 'USA'),
(2, 'ROBERT', 'LUNA', 22, 'USA'),
(3, 'DAVID', 'ROBINSON', 22, 'UK'),
(4, 'JOHN', 'REINHARDT', 25, 'UK'),
(5, 'BETTY', 'DOE', 28, 'UAE'),
(6, 'ALICE', 'SMITH', 35, 'USA'),
(7, 'MICHAEL', 'BROWN', 40, 'UK'),
(8, 'SARAH', 'DAVIS', 29, 'UAE'),
(9, 'TOM', 'WHITE', 31, 'USA'),
(10, 'EMMA', 'GREEN', 27, 'UK');

INSERT INTO ORDERS (ORDER_ID,ITEM,AMOUNT,CUSTOMER_ID) VALUES
(1, 'KEYBOARD', 400, 4),
(2, 'MOUSE', 300, 4),
(3, 'MONITOR', 12000, 3),
(4, 'KEYBOARD', 400, 1),
(5, 'MOUSEPAD', 250, 2),
(6, 'MONITOR', 10000, 6),
(7, 'KEYBOARD', 450, 6),
(8, 'MOUSE', 350, 7),
(9, 'MONITOR', 11000, 9),
(10, 'MOUSEPAD', 300, 10);

INSERT INTO SHIPPINGS (SHIPPING_ID,STATUS,CUSTOMER) VALUES
(1, 'PENDING', 2),
(2, 'PENDING', 4),
(3, 'DELIVERED', 3),
(4, 'PENDING', 5),
(5, 'DELIVERED', 1),
(6, 'DELIVERED', 6),
(7, 'PENDING', 7),
(8, 'DELIVERED', 9),
(9, 'PENDING', 8),
(10, 'DELIVERED', 10);