SELECT ORDER_ID, 
	   ORDERS.CUSTOMER_ID, 
	   ITEM, AMOUNT, 
	   SUM(AMOUNT) OVER (PARTITION BY ORDERS.CUSTOMER_ID) AS TOTAL_BY_CUSTOMER
FROM ORDERS
JOIN CUSTOMERS
ON CUSTOMERS.CUSTOMER_ID = ORDERS.CUSTOMER_ID 
ORDER BY ORDER_ID